apiVersion: v1
kind: Secret
metadata:
  name: pre-checker-secret
type: Opaque
data:
  reg-api-username: <username encrypted with base64>
  reg-api-password: <password encrypted with base64>
stringData:
  redis-host: <redis host>
  redis-port: "6379"
  academic-year: "2564"
  reg-api-get-students-path: https://apiv2.reg.cmu.ac.th/v2/student
  reg-api-get-student-courses-path: https://apiv2.reg.cmu.ac.th/v2/regist
