apiVersion: v1
kind: Service
metadata:
  name: auto-prerequisite-checker
  labels:
    run: auto-prerequisite-checker
spec:
  ports:
  - port: 3000
    nodePort: 30000
    protocol: TCP
  selector:
    run: auto-prerequisite-checker
  type: LoadBalancer
  